default: &default
  adapter: postgresql
  host: <%= ENV["DATABASE_HOST"] || 'localhost' %>
  username: <%= ENV["DATABASE_USERNAME"] || 'educite' %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: educite_development

test:
  <<: *default
  database: educite_test

production:
  <<: *default
  database: educite_production
  password: <%= ENV["DATABASE_PASSWORD"] %>
